[project]
name = "api-crud"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.116.2",
    "flask>=3.1.2",
    "gunicorn>=23.0.0",
]
